### ISSUE TITLE
Problems with cache busting on new release

### ISSUE THREAD

**Issue by colthreepv** [WDaan/VueTorrent#121]
When updating to a newer release of VueTorrent (BTW I really dig the new black style 🥳 GJ!)  
I always have the issue described here: https://github.com/vuejs-templates/pwa/issues/177

There is a valid workaround explained here https://github.com/stetrevor/vuejs-pwa-demo

I will be more thorough: ServiceWorkers only work over HTTPS (recent change), so the PWA part of vue-cli only affects the small amount of users that publish their qbittorrent webUI protected by SSL, this includes me.

What happens then, the basic implementation of the `@vue/cli-plugin-pwa` does indeed cache the app, but **TOO MUCH**, the website never gets updated, when I update with a new release, except if used `shift+ctrl+r`

**Comment by WDaan** [comment]
Possibly solved by #183?

**Comment by jef** [comment]
Hey @WDaan, still can't seem to bust this cache. I get the new version in the Settings modal, but categories aren't getting updated. Is this something else I should do? They appear in incognito.

**Comment by jef** [comment]
Let me know if I can give any more information or try anything for you.

**Comment by m4ximuel** [comment]
This problem occurred because the two image files pwa requested were missing. Perhaps this has been resolved in version 0.9.0.
Please let me know if the problem is reproduced.

**Comment by jef** [comment]
Refreshing did great and I got some of the new modals and some images! But for the categories, I still don't see  `Uploaded`. Although running in incognito this is part of the list.

**Comment by m4ximuel** [comment]
@jef please test this: #227
It is a patch that clearly complies with the service worker rules. It may require 2-3 refreshes after release.

**Comment by jef** [comment]
I'll checkout a build. Thanks!

**Comment by jef** [comment]
Built and using, but no avail. After a few refreshes, I got the change I made with the version linking, but no updating on the filtering.

Normal:

![image](https://user-images.githubusercontent.com/12074633/115446272-f336c380-a1e4-11eb-8197-05787ce214f0.png)

Incognito:

![image](https://user-images.githubusercontent.com/12074633/115446388-27aa7f80-a1e5-11eb-8d5e-56d58662f2e7.png)

---

Also scrolled to bottom, no `Uploaded`.

**Comment by m4ximuel** [comment]
@jef Um...Have you ever been item 'uploaded' missing from a previous version before I got involved?

**Comment by jef** [comment]
> Incidentally, the new service worker policy requires that all 'VueTorrent' processors be shut down for updates. need restart, not refresh

As in restart browser?

**Comment by WDaan** [comment]
Perhaps it has nothing to do with the service worker? All your settings are saved using vuex-persist into localstorage. When you launch VueTorrent, previous settings/state are loaded from localstorage. When new properties are added to the default settings, e.g. an uploaded property, they get overwritten by the old state that's retrieved from localstorage.

Deleting these settings from localstorage & then quickly refreshing before they get saved again will probably solve your problem.

I've allready mentioned this problem somewhere else, a refactor to use websql would be nice.

**Comment by m4ximuel** [comment]
@jef no need restart browser but no tabs should have VueTorrent open. I guess the problem @WDann mentions is correct

**Comment by jef** [comment]
> Deleting these settings from localstorage & then quickly refreshing before they get saved again will probably solve your problem.

For whatever reason, I thought I'd done this in the past. I went into Chrome (chrome://settings/siteData) and deleted the local storage from there. Deleting the local storage from the developer console and Application settings didn't work (like you mentioned, it auto populates too quickly).

I'll close for now. Thanks for both of your help and sorry for my ignorance ☺️

**Comment by WDaan** [comment]
I usually do in the the 'Application' Tab in Chrome Dev tools, but you have to be fast.
Did that actually solve your issue? 🙂 


No worries at all! You're right to open an issue, the application isn't behaving in a way that is to be expected... so it should indeed be fixed. I threw vuex-persist in there and called it a day aaaages ago, but the application should handle persisting data a lot smarter/more efficiënt.

**Comment by jef** [comment]
> Did that actually solve your issue though? 🙂

Yep! All set it seems.

> I threw vuex-persist in there and called it a day aaaages ago

All too familiar with this 😆

**Comment by sulliops** [comment]
This issue is rather noteworthy after upgrading to release 0.13.0 (which I did today because of this [fix](https://github.com/WDaan/VueTorrent/pull/310) for disabling authentication for setups behind reverse proxies). Reloading the page sends me right back to the login page, which should be disabled, because a service worker is caching the app status.

Full console message:
```
App is being served from cache by a service worker.
For more details, visit https://goo.gl/AFskqB
Service worker has been registered.
```

**Comment by WDaan** [comment]
Lets see if this issue changes with 1.0.0 Vite release

**Comment by WDaan** [comment]
Been rolling with this for a couple of days, new updates seem to come true just fine.

**Comment by jef** [comment]
Nice job @WDaan!
