### ISSUE TITLE
Card display options not saving on v2

### ISSUE THREAD

**Issue by 2fst4u** [WDaan/VueTorrent#1262]
On Firefox mobile. When I choose to select or deselect certain parts of the card display like selecting "tracker", it doesn't save when I open the web app next time.

**Comment by Larsluph** [comment]
Already fixed in #1244 but not yet released haha

**Comment by 2fst4u** [comment]
Sweet nice work

**Comment by philippetev** [comment]
This one is NOT fixed. Installed version 2.0.1 (the one that actually shows 2.0.0 in the settings page) and it remembers all settings, except the ones for the cards. Tried to reset the setting and set them again, cleared the browser data, but they are not saved. Happen in FF and Edge.
